default:
  image: node:22.12.0

.pnpm:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
    - export PATH=$PATH:$(pnpm bin)
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

stages:
  - test
  - build
  - deploy

test:
  extends:
    - .pnpm
  stage: test
  script:
    - pnpm install
    - pnpm lerna run test

build:
  extends:
    - .pnpm
  stage: build
  script:
    - pnpm install
    - node ./scripts/build.js
  artifacts:
    paths:
      - "packages/**/lib/"