default:
  image: node:22.13.1

.pnpm:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
    - export PATH=$PATH:$(pnpm bin)
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

stages:
  - build
  - test
  - deploy

build:
  extends:
    - .pnpm
  stage: build
  script:
    - pnpm install
    - node ./scripts/build.js
  artifacts:
    paths:
      - "packages/**/lib/"
    exclude:
      - "**/node_modules/**"

test:
  extends:
    - .pnpm
  stage: test
  dependencies:
    - build
  script:
    - pnpm install
    - pnpm lerna run test